#define DYNAMIC_KEYMAP_LAYER_COUNT 7
#define LAYER_STATE_8BIT

#define TAPPING_TOGGLE 2

#define AUTO_SHIFT_TIMEOUT 200
#define NO_AUTO_SHIFT_NUMERIC
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define RGB_MATRIX_KEYPRESSES